version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "270514764245"
    ECR_REGISTRY: "270514764245.dkr.ecr.us-east-1.amazonaws.com/static-website"

phases:
  install:
    runtime-versions:
      docker: 20
      aws-cli: 1.x
    commands:
      - echo "Installing dependencies"
      - sudo apt update -y
      - sudo apt install -y docker.io
      - pip install awscli
      - pip install docker-credential-ecr-login
      #- sudo systemctl start docker
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      -  $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t static-website .
      - docker tag static-website:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/static-website:latest
  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/static-website:latest
artifacts:
  files:
    - '**/*'
