version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "270514764245"
    ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/static-website"

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt update -y
      - sudo apt install -y docker.io
      - docker --version
      - pip install awscli
      - aws --version
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 270514764245.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t static-website .
      - docker tag static-website:latest 270514764245.dkr.ecr.us-east-1.amazonaws.com/static-website
  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push 270514764245.dkr.ecr.us-east-1.amazonaws.com/static-website
artifacts:
  files:
    - '**/*'
